### ISSUE TITLE
Neo4j - Integration MetricTransformer error

### ISSUE THREAD

**Issue by dmpduran** [DataDog/integrations-extras#1213]
Environment

    Neo4j version : 4.3.9
    Datadog Agent version : 7
    Neo4j integration version : 2.0.0

/etc/datadog-agent/conf.d/neo4j.d/conf.yaml file content

    instances:
      - openmetrics_endpoint: http://localhost:2004/metrics
        neo4j_version: '4.3.9'
        neo4j_dbs: [neo4j]

Error executing the command "datadog-agent check neo4j"

    neo4j (2.0.0)
    -------------
      Instance ID: neo4j:1934d228d1ea55c5 [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/neo4j.d/conf.yaml
      Total Runs: 2
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 1ms
      Last Execution Date : 2022-02-22 20:10:19 UTC (1645560619000)
      Last Successful Execution Date : Never
      Error: 'MetricTransformer' object has no attribute 'add_custom_transformer'
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 992, in run
          initialization()
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/neo4j/neo4j.py", line 69, in configure_additional_transformers
          metric_transformer.add_custom_transformer(
      AttributeError: 'MetricTransformer' object has no attribute 'add_custom_transformer'

**Comment by yzhan289** [comment]
Pinging neo4j maintainer @davidfauth.

**Comment by dmpduran** [comment]
Hi @yzhan289 

Thanks for your message.

For the current Datadog version, which Neo4j integration I need to use?

The objective is to work with Neo4j 4.3.9 version with different database name.

Thanks in advance!

**Comment by yzhan289** [comment]
Hi @dmpduran, it looks like Neo4j 4.x is supported starting on integration version 2.0.0: https://github.com/DataDog/integrations-extras/pull/944. This means if you have Neo4j version 4.3.9, the current 1.x version of the integration will not work properly.

**Comment by dmpduran** [comment]
Hi @yzhan289,

Will not be possible. We need to use another solution in the meantime.

Thanks for the quick support! 👍

**Comment by yzhan289** [comment]
No problem. I'll close this ticket for now, but 7.34 should be released fairly soon. Thank you for your patience!
