### ISSUE TITLE
Issues running on filebeat 6.3.0

### ISSUE THREAD

**Issue by danielkasen** [DataDog/integrations-extras#167]
It would appear that the client doesn't want to work on 6.3.0 now that you can fix the registry permissions. You now get this error in the output:

> `2018-06-20 18:07:24 UTC | ERROR | (runner.go:276 in work) | Error running check filebeat: [{"message": "'list' object has no attribute 'itervalues'", "traceback": "Traceback (most recent call last):\n  File \"/opt/datadog-agent/bin/agent/dist/checks/__init__.py\", line 332, in run\n    self.check(copy.deepcopy(self.instances[0]))\n  File \"/etc/datadog-agent/checks.d/filebeat.py\", line 30, in check\n    for item in registry_contents.itervalues():\nAttributeError: 'list' object has no attribute 'itervalues'\n"}]`

Example of my registry:

`[
  {
    "FileStateOS": {
      "device": 51713,
      "inode": 33246
    },
    "type": "log",
    "ttl": -1,
    "timestamp": "2018-06-20T17:36:57.928067509Z",
    "offset": 0,
    "source": "/var/log/ansible-pull.log"
  },
  {
    "FileStateOS": {
      "device": 51713,
      "inode": 161944
    },
    "type": "log",
    "ttl": -1,
    "timestamp": "2018-06-20T18:07:33.128583217Z",
    "offset": 9173,
    "source": "/var/log/datadog/trace-agent.log"
  }
}
]`

**Comment by danielkasen** [comment]
Don't think I can do PR for this repo but this is a quick fix:

```
diff --git a/filebeat/check.py b/filebeat/check.py
index 4abec70..ee8869c 100644
--- a/filebeat/check.py
+++ b/filebeat/check.py
@@ -27,7 +27,7 @@ class FilebeatCheck(AgentCheck):

         registry_contents = self._parse_registry_file(registry_file_path)

-        for item in registry_contents.itervalues():
+        for item in registry_contents:
             self._process_registry_item(item)

     def _parse_registry_file(self, registry_file_path):
```

**Comment by ChristineTChen** [comment]
Closing PR as this issue is addressed in https://github.com/DataDog/integrations-extras/pull/189
